/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visao;

import dao.Banco;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import modelo.Fornecedor;


/**
 *
 * @author labc
 */
public class TelaFornecedor extends javax.swing.JFrame {
    
 DefaultTableModel tmFornecedor = new DefaultTableModel (null, new String[]{ "codigofornecedor","nomefornecedor","contatofornecedor"});

List<Fornecedor> fornecedores;

ListSelectionModel lsmFornecedor;
    
    public TelaFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        codigofornecedor = new javax.swing.JTextField();
        contatofornecedor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelafornecedor = new javax.swing.JTable();
        sairfornecedor = new javax.swing.JButton();
        excluirfornecedor = new javax.swing.JButton();
        editarfornecedor = new javax.swing.JButton();
        novofornecedor = new javax.swing.JButton();
        salvarfornecedor = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        pesquisarfornecedor = new javax.swing.JButton();
        nomefornecedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fornecedor");
        setUndecorated(true);

        jLabel1.setText("Nome:");

        jLabel2.setText("Contato:");

        jLabel4.setText("Codigo:");

        codigofornecedor.setBackground(new java.awt.Color(204, 204, 204));
        codigofornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigofornecedorActionPerformed(evt);
            }
        });

        tabelafornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4"
            }
        ));

        jScrollPane2.setViewportView(tabelafornecedor);

        sairfornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Close.png"))); // NOI18N
        sairfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairfornecedorActionPerformed(evt);
            }
        });

        excluirfornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lixeira.png"))); // NOI18N
        excluirfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirfornecedorActionPerformed(evt);
            }
        });

        editarfornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Editar.png"))); // NOI18N
        editarfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarfornecedorActionPerformed(evt);
            }
        });

        novofornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Novo.png"))); // NOI18N
        novofornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novofornecedorActionPerformed(evt);
            }
        });

        salvarfornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        salvarfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarfornecedorActionPerformed(evt);
            }
        });

        pesquisarfornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pesquisar.png"))); // NOI18N
        pesquisarfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarfornecedorActionPerformed(evt);
            }
        });

        jLabel3.setText("Pesquisar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pesquisarfornecedor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel1)
                                    .addGap(361, 361, 361))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(contatofornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(codigofornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(nomefornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(187, 187, 187)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(salvarfornecedor, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(excluirfornecedor, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(editarfornecedor, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(novofornecedor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sairfornecedor, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesquisarfornecedor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(novofornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salvarfornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarfornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirfornecedor))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(codigofornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomefornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contatofornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sairfornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        setSize(new java.awt.Dimension(478, 340));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sairfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairfornecedorActionPerformed
        this.dispose();
    }//GEN-LAST:event_sairfornecedorActionPerformed

    private void codigofornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigofornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigofornecedorActionPerformed

    private void novofornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novofornecedorActionPerformed
 limpar();
    }                                       

    public void limpar(){
        nomefornecedor.setText("");
        contatofornecedor.setText(""); 
        nomefornecedor.requestFocus(); 
    
    }//GEN-LAST:event_novofornecedorActionPerformed

    private void salvarfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarfornecedorActionPerformed
        try {
            Fornecedor c = new Fornecedor();
            c.setnomefornecedor(nomefornecedor.getText());
            c.setcontatofornecedor(contatofornecedor.getText());
            Banco dao = new Banco();
            dao.adicionarFornecedor(c);
            JOptionPane.showMessageDialog(null, "incluido com sucesso");
            limpar();
            desabilitar();
            habilitar ();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_salvarfornecedorActionPerformed

    private void excluirfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirfornecedorActionPerformed
     try{
         Banco banco = new Banco();
         banco.excluirFornecedor(Integer.parseInt(JOptionPane.showInputDialog("Informe o codigo a ser excluido")));
         JOptionPane.showMessageDialog(null, "Registro Excluido com Sucesso");
         LimparDados();
         desabilitaDados();
         sairfornecedor.setEnabled(true);
         excluirfornecedor.setEnabled(false);
         novofornecedor.setEnabled(true);
         editarfornecedor.setEnabled(false);
     } catch(Exception e ){
         System.out.println(e.getMessage());
     }   
    }//GEN-LAST:event_excluirfornecedorActionPerformed

    private void editarfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarfornecedorActionPerformed
        try{
            int opcao=JOptionPane.showConfirmDialog(null, "Deseja realizar  alteração no registro?","Atenção",JOptionPane.YES_NO_OPTION);
            if(opcao==JOptionPane.YES_NO_OPTION){
                Fornecedor c=new Fornecedor();
                c.setcodigofornecedor(Integer.valueOf(codigofornecedor.getText()));
                c.setnomefornecedor(String.valueOf(nomefornecedor.getText()));
                c.setcontatofornecedor(String.valueOf(contatofornecedor.getText()));
                Banco banco =new Banco();
                banco.alterarFornecedor(c);
                JOptionPane.showConfirmDialog(null, "Alteração Efetuada com sucesso");
                desabilitaDados();
                editarfornecedor.setEnabled(false);
                excluirfornecedor.setEnabled(true);
                sairfornecedor.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(null, "Alteração não realizada");
                desabilitaDados();         
            }
        } catch(Exception e ){
            e.printStackTrace();
        }
    }//GEN-LAST:event_editarfornecedorActionPerformed

    private void pesquisarfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarfornecedorActionPerformed
      
    }//GEN-LAST:event_pesquisarfornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigofornecedor;
    private javax.swing.JTextField contatofornecedor;
    private javax.swing.JButton editarfornecedor;
    private javax.swing.JButton excluirfornecedor;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nomefornecedor;
    private javax.swing.JButton novofornecedor;
    private javax.swing.JButton pesquisarfornecedor;
    private javax.swing.JButton sairfornecedor;
    private javax.swing.JButton salvarfornecedor;
    private javax.swing.JTable tabelafornecedor;
    // End of variables declaration//GEN-END:variables

        private void desabilitar() {
        nomefornecedor.setEditable(false);
        contatofornecedor.setEditable(false);
       
    }

    private void habilitar() {
        nomefornecedor.setEditable(true);
        contatofornecedor.setEditable(true);
    }
    
    public void LimparDados (){
        nomefornecedor.setText("");
        contatofornecedor.setText("");
    } 
    
        public boolean verificaDados() {
if (!nomefornecedor.getText().equals("")&& !contatofornecedor.getText().equals("")){
return true;
} else {
JOptionPane.showMessageDialog(null, "Os campos nome ou quantidade nao foram preenchidos");
return false;
}
}
        
private void alterarFornecedor () throws Exception {
if (tabelafornecedor.getSelectedRow() != -1) {
if (verificaDados()){
Fornecedor c1 = new Fornecedor ();
Banco dao = new Banco();
c1.setcodigofornecedor(Integer.valueOf(codigofornecedor.getText()));
c1.setnomefornecedor(String.valueOf(nomefornecedor.getText()));
c1.setcontatofornecedor(String.valueOf(contatofornecedor.getText()));
dao.alterarFornecer (c1);
JOptionPane.showMessageDialog(null, "Dados alterados com sucesso");
}
}
}

     public void desabilitaDados () {
        codigofornecedor.setEditable(false);
        nomefornecedor.setEditable(false);
        contatofornecedor.setEditable(false);
} 
     

      private void mostrarpesquisa (List <Fornecedor> fornecedores){
while (tmFornecedor.getRowCount() > 0) {
tmFornecedor.removeRow(0);
}
if (fornecedores.size() == 0) {
JOptionPane.showMessageDialog (null, "nenhum Fornecedor Cadastrado");
} else {
String[] linha = new String[] {null, null, null,};
for (int i = 0; i < fornecedores.size(); i++){

tmFornecedor.addRow(linha);
tmFornecedor.setValueAt (fornecedores.get(i).getcodigofornecedor(), i, 0);
tmFornecedor.setValueAt (fornecedores.get(i).getnomefornecedor(), i, 1);
tmFornecedor.setValueAt (fornecedores.get(i).getcontatofornecedor(), i, 2);

}
}
}
      private void tabelafornecedorLinhaSelecionada (JTable tabela){
if (tabelafornecedor.getSelectedRow() != -1){
habilitaDados();
codigofornecedor.setText (String.valueOf (fornecedores.get(tabela.getSelectedRow()).getcodigofornecedor()));
nomefornecedor.setText(fornecedores.get(tabela.getSelectedRow()).getnomefornecedor());
contatofornecedor.setText(fornecedores.get(tabela.getSelectedRow()).getcontatofornecedor());
} else {
LimparDados ();
}
      }    
private void alterarProduto () throws Exception {
if (tabelafornecedor.getSelectedRow() != -1) {
if (verificaDados()){
Fornecedor c1 = new Fornecedor ();
Banco dao = new Banco();
c1.setcodigofornecedor(Integer.valueOf(codigofornecedor.getText()));
c1.setnomefornecedor(String.valueOf(nomefornecedor.getText()));
c1.setcontatofornecedor(String.valueOf(contatofornecedor.getText()));
dao.alterarFornecer (c1);
JOptionPane.showMessageDialog(null, "Dados alterados com sucesso");
}
}
}
public void habilitaDados () {
        nomefornecedor.setEditable(true);
        contatofornecedor.setEditable(true);
    
    }
    }
